development:
  adapter: postgresql
  database: nebulr_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: nebulr_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: nebulr_production
  pool: 5
  timeout: 5000
